version: '3.4'

services:
  ordermanagement:
    image: ordermanagementsystem
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
